# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://khorevaa.github.io/initiative-group-homestead/
title: Создание инициативной группы по организации поселения родовых поместий
email: horevaa@yandex.ru
author: Хорев Алексей
description: > # "Write an awesome description for your new site here. 
  Сайт по организации создания поселения родовых поместий.
  КОБ, Мертвая Вода, ВП СССР, ДОТУ, Мерге, В. Мерге, Анастасия, Экопоселение.
copyright: 'Copyright &copy; 2017 Khorev A.A.. Все права защищены.'
credits: 'Сайт создан для организации инициативной группы поселения родовых поместий.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: vk
    url: https://vk.com/club153296725
  - title: facebook
    url: https://vk.com/club153296725
  - title: github
    url: https://github.com/Khorevaa/initiative-group-homestead
  